title: Colombia: Capacity Building Work Plan for the Amazonia
description: La página de contenido de los talleres de capacitación
baseurl: "/colombia-training" # the subpath of your site, e.g. /blog
url: "https://servir-amazonia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/transparent-logos.png"

remote_theme: just-the-docs/just-the-docs
